export const HOME = '/'
export const LOGIN = '/login'
export const CARTPAGE = '/mycart'
export const FILTERPAGE = '/filterpage'
export const PRODUCT = '/product/:id'
export const CHECKOUT = '/checkout'
export const THANKYOUPAGE = '/yourpurchase'
export const PRIVATE = '/private'
export const LOGOUT = '/private/logout'
export const WISHLIST = '/private/wishlist'

